name: Helm Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.18.2

    - name: Run Helm template dry-run
      run: |
        helm template --dry-run test ${{ github.workspace }}/dummy-helm > /dev/null
